### ISSUE TITLE
当开启  Allow access to file URLs 的时候无法访问保存的对照翻译网页

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/next-immersive-translate#1]
对照翻译后，如果将内容保存成 html，重新打开网页，对照翻译会自动消失，如果关闭 
Allow access to file URLs 则可以避免该问题。这看起来是个 bug，因为其他对照翻译插件没有这样的问题，看起来也不像有意设计。但有时候的确是需要长期开启 
Allow access to file URLs 以便翻译本地 html 文件的，bug 很难在不妨碍正常功能的情况下被简单消除。

**Comment by theowenyoung** [comment]
谢谢反馈，这是bug～ 似乎是插件在启动的时候会做一些清理。

**Comment by theowenyoung** [comment]
最新版本已解决这个问题
