### ISSUE TITLE
文章中超链接的处理存在问题

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/next-immersive-translate#10]
![image](https://user-images.githubusercontent.com/38101170/211174092-13bc251b-f2fb-4634-80fb-05fe0a1f9fe6.png)

可以看到原本完整的段落被切分了，影响了阅读的体验

# 划词翻译的处理方法
![image](https://user-images.githubusercontent.com/38101170/211174126-00c78d85-f575-4445-8b42-e5684bfd3ecc.png)

# links
[Could the Kynurenine Pathway Be Causing ME/CFS, FM and Long COVID? - Health Rising --- 犬尿氨酸途径会导致 ME/CFS、FM 和长 COVID 吗？ - 健康崛起](https://www.healthrising.org/blog/2023/01/07/kynurenine-chronic-fatigue-fibromyalgia-long-covid/#comment-1062782)

**Comment by theowenyoung** [comment]
试下最新版，已兼容

**Comment by Andy-AO** [comment]
> 试下最新版，已兼容

对行内元素的识别好像仍然存在问题

![image](https://user-images.githubusercontent.com/38101170/211221016-00635c84-ebbc-43a4-999c-7f6caa61ec38.png)

![image](https://user-images.githubusercontent.com/38101170/211221027-c3b64599-73e1-492b-91cf-fa1ffb65610d.png)


# links
[T helper cell - Wikipedia](https://en.wikipedia.org/wiki/T_helper_cell#Th1/Th2_model)

**Comment by theowenyoung** [comment]
已确认。修复的代码已经在构建了，几分钟后下载新版试试。

**Comment by Andy-AO** [comment]
> 已确认。修复的代码已经在构建了，几分钟后下载新版试试。

已升级到新版，但是别的网页有问题

![image](https://user-images.githubusercontent.com/38101170/211236164-dc8d8c88-97c7-440c-9c57-f774439f613d.png)

# links
[Diagnosis and Treatment of Supine Hypertension in Autonomic Failure Patients With Orthostatic Hypotension - PMC --- 直立性低血压自主神经衰竭患者仰卧位高血压的诊治 - PMC](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8099208/)

**Comment by theowenyoung** [comment]
感谢反馈，最新版本已解决

**Comment by BruceLee569** [comment]
这个网页的链接还是不显示：https://www.pythonguis.com/pyqt6/
