### ISSUE TITLE
在部分页面上直接出现 HTML

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/next-immersive-translate#11]
![image](https://user-images.githubusercontent.com/38101170/211220055-97331d66-3fab-4a94-acd1-797eec92ec87.png)

# links
[Could the Kynurenine Pathway Be Causing ME/CFS, FM and Long COVID? - Health Rising --- 犬尿氨酸途径会导致 ME/CFS、FM 和长 COVID 吗？ - 健康崛起](https://www.healthrising.org/blog/2023/01/07/kynurenine-chronic-fatigue-fibromyalgia-long-covid/#comment-1062782)

**Comment by Andy-AO** [comment]
已更新到新版

**Comment by theowenyoung** [comment]
已确认。修复的代码已经在构建了，几分钟后下载新版试试。
