### ISSUE TITLE
清除缓存后的缓存大小计算可能是有问题的

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/next-immersive-translate#12]
清除缓存之后发现这个缓存大小的计算总是进行中，很长时间都不会出结果，清除之后应该是0，很好统计，不应该出现计算时间太长的问题

![image](https://user-images.githubusercontent.com/38101170/211220640-db3f2f23-e8c1-431a-87ac-86dd685f431d.png)

**Comment by Andy-AO** [comment]
![image](https://user-images.githubusercontent.com/38101170/211220705-3c57898c-d3b4-4f6b-84bc-589d315dd8f0.png)

**Comment by Andy-AO** [comment]
又过了很长时间，仍然在计算中基本上可以确定是有问题的，猜测永远不会计算出来

![image](https://user-images.githubusercontent.com/38101170/211221060-df14e326-1265-46c0-abca-6df0159c2225.png)

**Comment by theowenyoung** [comment]
你可以 点击 左下角 开发者设置， 在那里 打开 日志， 然后在页面上 右键 ，审查元素， 然后看下里面的 Console 里的日志输出。看看有没有错误。 我这边测试缓存清理，好像一直没有遇到问题。

**Comment by Andy-AO** [comment]
> 你可以 点击 左下角 开发者设置， 在那里 打开 日志， 然后在页面上 右键 ，审查元素， 然后看下里面的 Console 里的日志输出。看看有没有错误。 我这边测试缓存清理，好像一直没有遇到问题。

![image](https://user-images.githubusercontent.com/38101170/211223391-2a89e979-7830-40a4-aab8-d60495b11b24.png)


![image](https://user-images.githubusercontent.com/38101170/211223334-44ec5e74-18c4-47ca-b2b3-380e8631885d.png)

问题依然出现了，我也开启了调试啊，这是控制台上的内容


我想我换个平台测试吧，这样嗯，就可以排除是由于平台或者是更新的时候，弄坏了什么文件导致的问题，因为现在更新基本上都是手动覆盖的

**Comment by theowenyoung** [comment]
也没有出错的日志

**Comment by theowenyoung** [comment]
最新版本里，我彻底重写了 消息通信。 不知道是否该问题导致。 你可以再试试。如果还有问题再研究。

**Comment by theowenyoung** [comment]
@b1tg  我添加了 读取缓存超时后，发现还想的确会有超时的情况。这个会是什么原因呢。是不是我们操作indexDB的时候，没有处理好复用连接池问题，还是说大量读取的时候确实有几率超时？

**Comment by theowenyoung** [comment]
这个问题和 #7 似乎是类似的原因。另一个问题里 有很多视频截图。我今天应该算是排除了 通信机制的问题，我完全重写了通信，用正确率更好的 onConnect 代替 onMessage.

**Comment by Andy-AO** [comment]
> 最新版本里，我彻底重写了 消息通信。 不知道是否该问题导致。 你可以再试试。如果还有问题再研究。

好的。不过我关闭了缓存之后，感觉使用还是很顺畅的，就让我怀疑缓存的必要性，这个机制太复杂了。

**Comment by Andy-AO** [comment]
> 这个问题和 #7 似乎是类似的原因。另一个问题里 有很多视频截图。我今天应该算是排除了 通信机制的问题，我完全重写了通信，用正确率更好的 onConnect 代替 onMessage.

问题确实依旧存在啊


https://user-images.githubusercontent.com/38101170/211445963-361dc9b5-d2d9-4b07-9e05-9c767656b21b.mp4

**Comment by b1tg** [comment]
> @b1tg  我添加了 读取缓存超时后，发现确实会有超时的情况。这个会是什么原因呢？是不是我们操作indexDB的时候，没有处理好复用连接池问题，还是说大量读取的时候确实有几率超时？

超时可能是旧的连接未释放，删除操作被阻塞，一直等到几分钟后触发GC老的连接被清除，删除才能成功。试一下新分支。

**Comment by theowenyoung** [comment]
@Andy-AO 已将此修复发布新版，再观察下吧。 缓存机制本来并没有引入特别复杂的概念，就是普通的键值对存储。 只不过这里用了indexDB实现的存储，因为indexDB的大小是不受限制的，所以作为持久的缓存更有意义一点。

缓存对网页翻译带来的好处非常多，所以这个机制本身是很有意义的。

**Comment by Andy-AO** [comment]
> @Andy-AO 已将此修复发布新版，再观察下吧。 缓存机制本来并没有引入特别复杂的概念，就是普通的键值对存储。 只不过这里用了indexDB实现的存储，因为indexDB的大小是不受限制的，所以作为持久的缓存更有意义一点。
> 
> 缓存对网页翻译带来的好处非常多，所以这个机制本身是很有意义的。

昨天，测试完成之后忘记关闭缓存了，然后问题又出现了，才想到重新关闭缓存。

至少在我的使用场景下，没有观察到两者有什么显著区别，或许重复翻译相同的网页，这个机制是有用的，但我不清楚他对不同网页带来的查询的负担，和他翻译相同网页带来的好处哪个更大，这个可能和个人的使用习惯有关。

这就测试下，看看是不是已经解决了。

**Comment by Andy-AO** [comment]
测试发现该问题已解决

**Comment by theowenyoung** [comment]
对，主要是两点：
一个是重复网页的翻译可以节省很多资源，这里面一方面是来自于对重复打开相关网页，另一个是比如你在浏览推特时间轴的时候，从主页到详情页，然后再返回到主页，这个时候其实是触发重新翻译的动作的，这种情况下就会用到缓存。

第二个页面上的常用的比较短的词语，重复的频率很高。
