### ISSUE TITLE
通过覆盖的方式更新Chrome扩展，会导致其暂时失效

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/next-immersive-translate#14]
现在也没有上架应用商店，只能用开发者模式加载包的方式来使用扩展，更新的时候也是解压之后直接覆盖，这样更新虽然能够成功，但是会失效，然后不知道怎么样又突然有效了，这个很奇怪。

失效主要体现在虽然扩展版本到最新版了，也可以点击打开界面，但是按了翻译之后完全没反应，自动翻译也是没反应。

不知道是不是我的更新方式有问题。

**Comment by theowenyoung** [comment]
可以通过[同步git 仓库的方式](https://immersive-translate.owenyoung.com/installation#%E6%88%96%E8%80%85%E9%80%9A%E8%BF%87-github-repo-%E8%BF%BD%E8%B8%AA%E6%9B%B4%E6%96%B0)进行更新：

    git clone https://github.com/immersive-translate/next-immersive-translate.git

扩展位于dist/chrome, dist/firefox, dist/userscript 中。

**Comment by Andy-AO** [comment]
> 可以通过[同步git 仓库的方式](https://immersive-translate.owenyoung.com/installation#%E6%88%96%E8%80%85%E9%80%9A%E8%BF%87-github-repo-%E8%BF%BD%E8%B8%AA%E6%9B%B4%E6%96%B0)进行更新：
> 
> ```
> git clone https://github.com/immersive-translate/next-immersive-translate.git
> ```
> 
> 扩展位于dist/chrome, dist/firefox, dist/userscript 中。扩展位于dist/chrome, dist/firefox, dist/userscript 中。

好的，下次更新试试

**Comment by theowenyoung** [comment]
刚提交了一个版本，这个版本支持 长段落 自动断句，可以在“界面设置” 里开启。

**Comment by Andy-AO** [comment]
直接克隆是不行的
```PowerShell
PS>git clone https://github.com/immersive-translate/next-immersive-translate.git
fatal: destination path 'next-immersive-translate' already exists and is not an empty directory.
```
先删除，再克隆发现可以了，数据也没丢
```PowerShell
PS>Remove-Item next-immersive-translate -Recurse -Force; git clone https://github.com/immersive-translate/next-immersive-translate.git
Cloning into 'next-immersive-translate'...
remote: Enumerating objects: 1392, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 1392 (delta 23), reused 20 (delta 13), pack-reused 1351
Receiving objects: 100% (1392/1392), 3.51 MiB | 3.82 MiB/s, done.
Resolving deltas: 100% (1027/1027), done.
```
但问题依然存在，按下去没反应

**Comment by theowenyoung** [comment]
暂时失效指的是？ 安装后，应该至少需要重新刷新网页才能使用。

**Comment by Andy-AO** [comment]
> 暂时失效指的是？ 安装后，应该至少需要重新刷新网页才能使用。

我记得是这么回事，重新刷新网页依然不能使用，因为打开新的网页也不行，但是重新启动浏览器就行了。

感觉不应该出现这种情况，因为我替换之前往往就已经把浏览器给关了，所以说应该不存在脚本没有生效的原因，毕竟浏览器本来就处于关闭的状态。

不过这个问题也不严重，就是多关一次浏览器。忽略也可以，或许到应用市场上更新了这个问题就没有了吧。

https://user-images.githubusercontent.com/38101170/211985328-8510be01-ec2b-4f9e-8e2d-6e037c173581.mp4

**Comment by Andy-AO** [comment]
视频上没有展示整个过程，因为是你回复之前我拍的，所以不许有针对性。如果你认为可以忽略那就关闭这个 issue，不忽略的话我可以拍个完整的视频。

**Comment by theowenyoung** [comment]
<img width="883" alt="image" src="https://user-images.githubusercontent.com/62473795/211985987-67361466-f14b-4537-99ca-8fe0d06eb905.png">

你替换之后，有没有点击 reload， 重新加载？

如果没有的话，那浏览器一般并不会自动识别到更新。下载更新后，尝试点击一下reload

**Comment by Andy-AO** [comment]
> <img alt="image" width="883" src="https://user-images.githubusercontent.com/62473795/211985987-67361466-f14b-4537-99ca-8fe0d06eb905.png">
> 
> 你替换之后，有没有点击 reload， 重新加载？
> 
> 如果没有的话，那浏览器一般并不会自动识别到更新。下载更新后，尝试点击一下reload

这个没有，我认为不太可能是这样的原因，因为我发现版本号已经更新成功了，我认为不存在只更新版本号，然后不更新功能的情况，所以我就没往这方面考虑。

我这就测试下。

**Comment by Andy-AO** [comment]
经过测试，的确要手动 reload，如果只是关闭浏览器，重新打开的话，版本号可能是对的，但功能可能是不能用的。问题已经解决，谢谢！
