### ISSUE TITLE
不翻译 sciencedirect 的主要区域

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/next-immersive-translate#15]
![image](https://user-images.githubusercontent.com/38101170/212165182-f570eb1d-aef5-44b9-b118-e30cf73a12f9.png)

![image](https://user-images.githubusercontent.com/38101170/212165192-2f46a484-003b-4e5d-b564-f4b75f6d58b5.png)

sciencedirect 网页的主要区域没有识别和翻译

# links
- [Oral pilocarpine (5 mg t.i.d.) used for xerostomia causes adverse effects in Japanese - ScienceDirect --- 用于口干症的口服毛果芸香碱（5 mg t.i.d.）在日本会引起不良反应 - ScienceDirect](https://www.sciencedirect.com/science/article/abs/pii/S0385814608000862)

**Comment by theowenyoung** [comment]
有更新到最新版吗？我这是可以翻译的。

**Comment by Andy-AO** [comment]
> 有更新到最新版吗？我这是可以翻译的。

确认版本是最新的

![image](https://user-images.githubusercontent.com/38101170/212169767-27d6723b-b907-4d20-98d7-50684388c027.png)

开启全部翻译就可以翻译了，如果不开启的话就翻译不了。我发现能识别成功，因为有动画，但是那个动画消失之后翻译没出现。

**Comment by theowenyoung** [comment]
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/62473795/212170703-0b4e9288-bce0-41eb-9710-d105ce6a4579.png">
会是缓存导致的吗？多刷新看看呢。

**Comment by Andy-AO** [comment]
> <img alt="image" width="1385" src="https://user-images.githubusercontent.com/62473795/212170703-0b4e9288-bce0-41eb-9710-d105ce6a4579.png">
> 
> 会是缓存导致的吗？多刷新看看呢。

关闭缓存，问题依旧， 有对应网页的报错

![image](https://user-images.githubusercontent.com/38101170/212171107-c5c99b26-2f94-485a-940c-003e609df25a.png)

**Comment by theowenyoung** [comment]
deadline 错误只是缓存超时，不影响使用。

你可以看看对应网页里的 console 控制台的日志。

**Comment by theowenyoung** [comment]
会不会是不同插件的相互影响？

**Comment by Andy-AO** [comment]
> 会不会是不同插件的相互影响？

已经考虑该因素，所以在隐私窗口中进行过测试，那个模式中基本上没有可用的扩展和脚本，但是问题仍然存在。既然有这种考虑，我准备换个浏览器测试下，看看怎么样。

**Comment by theowenyoung** [comment]
我复现了，似乎是自动翻译的时候，它会有问题。 但是整个网页加载完成后，手动点击翻译，或使用快捷键翻译，则结果正常。

**Comment by theowenyoung** [comment]
我给这个网站加一个延迟应该就可以了，似乎是这个完成在首次加载完成后，又重新更改了布局。

**Comment by theowenyoung** [comment]
好吧，似乎还是不行，而且好像还是浏览器相关，我用firefox测试是正常的，但是edge就无法渲染结果。我再研究下

**Comment by Andy-AO** [comment]
> 我给这个网站加一个延迟应该就可以了，似乎是这个完成在首次加载完成后，又重新更改了布局。

我在chrome里面反而复现不出来了，然后我按照你你的说法，结果复现出来，的确在这个浏览器中会出现这种情况，而且每次都会出现手动就不会出现，我也观察到了布局的变化。

其他插件也有类似的问题，划词翻译在自动翻译的时候，这个网页中表现更差。

**Comment by Andy-AO** [comment]
> 好吧，似乎还是不行，而且好像还是浏览器相关，我用firefox测试是正常的，但是edge就无法渲染结果。我再研究下

我现在想是不是应该放弃edge，😂

**Comment by theowenyoung** [comment]
好吧，我忘记reload了，加了延迟2秒后，edge里也一切正常，我更新了规则，2分钟生效，然后在about页面刷新一下即可。

**Comment by theowenyoung** [comment]
不过，下次遇到类似问题的时候，可以试试用 `alt+a`快捷键快速显示原文，然后再`alt+a` 显示翻译，这样一般就可以了。

**Comment by Andy-AO** [comment]
> 不过，下次遇到类似问题的时候，可以试试用 `alt+a`快捷键快速显示原文，然后再`alt+a` 显示翻译，这样一般就可以了。

好的

按那个翻译全部区域的快捷键它就可以了。我报告的主要考虑是怕他潜藏的更严重的问题，毕竟bug早修的话可能会容易些。结果查出来可能只是浏览器的问题。谢谢啦，辛苦。
