### ISSUE TITLE
US CDC 网站上的有些折叠内容不能翻译

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/next-immersive-translate#16]
考虑到这些内容可能是后来出现的，所以进行了全部翻译和切换翻译状态，可是仍然不行，在chrome上似乎也是这样

![image](https://user-images.githubusercontent.com/38101170/212184309-52a62aaa-f235-4f4b-b0e5-dc94c36236dc.png)
# links
[Possible Causes | Myalgic Encephalomyelitis/Chronic Fatigue Syndrome (ME/CFS) | CDC --- 可能原因 |肌痛性脑脊髓炎/慢性疲劳综合症 (ME/CFS) | CDC](https://www.cdc.gov/me-cfs/about/possible-causes.html)

**Comment by Andy-AO** [comment]
![image](https://user-images.githubusercontent.com/38101170/212184537-24f90cbe-1cb5-4de5-ab1f-3b066e3f53b4.png)
其他扩展是正常的

**Comment by theowenyoung** [comment]
确认。

但是似乎这样是ok的，默认不翻译的情况下，手动展开这个tab，这个时候再翻译，它就能识别。

我记得手机版维基百科，似乎也有类似问题，我看看有没有办法解决。

**Comment by theowenyoung** [comment]
可以了，更新最新版试试。

**Comment by Andy-AO** [comment]
经测试，该问题已解决，谢谢
