### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by Leechael** [immersive-translate/next-immersive-translate#18]
> 我创建了 https://www.buzzing.cc/ ，这是一款聚合外网可信度高的权威媒体以及社交媒体里的热门讨论，我使用 Deelp 将标题翻译为中文，以便母语使用者可以快速浏览以获得自己感兴趣的内容。没有废话，没有登录，有良好的 RSS 支持，以及最大化页面的信息密度。同时也支持无图模式，以减少分心。

Deelp -> DeepL

**Comment by theowenyoung** [comment]
Thanks! Corrected it!
