### ISSUE TITLE
在维基百科上会出现大量空白

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/next-immersive-translate#2]
# 异常情况
![image](https://user-images.githubusercontent.com/38101170/210669890-5e297c04-9605-4e53-9490-66563fe892ea.png)
# 正常情况
![image](https://user-images.githubusercontent.com/38101170/210669957-b9b38418-8fbc-45db-889c-e46941cd34bb.png)
在其他插件上没有该问题

**Comment by Andy-AO** [comment]
在其他网页上也会有类似问题
![image](https://user-images.githubusercontent.com/38101170/210670320-79b735a6-a17e-48ab-8dcd-8c0e5ae8f44d.png)

**Comment by Andy-AO** [comment]
有时候相当夸张，很影响阅读
![image](https://user-images.githubusercontent.com/38101170/210671560-e591f6af-6791-44b8-be48-4b274db7271e.png)

**Comment by theowenyoung** [comment]
谢谢反馈，可以分享一下有问题的网址吗？

**Comment by Andy-AO** [comment]
> 谢谢反馈，可以分享一下有问题的网址吗？

https://en.wikipedia.org/wiki/Herpesviridae

**Comment by theowenyoung** [comment]
好的～ 我研究一下～

**Comment by theowenyoung** [comment]
最新版已解决该问题， 请选择 支持的主题， 比如下划线等等， 像这种块状的译文主题，无法支持不换行。

**Comment by Andy-AO** [comment]
> 最新版已解决该问题， 请选择 支持的主题， 比如下划线等等， 像这种块状的译文主题，无法支持不换行。

这样啊，本来以为是可以实现的，因为之前用的插件是相同的样式，他们是已经实现的。是否可以参考其设计？插件的名字是「划词翻译」

[划词翻译 - Chrome 应用商店](https://chrome.google.com/webstore/detail/%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91/ikhdkkncnoglghljlkmcimlnlhkeamad)

**Comment by theowenyoung** [comment]
好吧，谢谢反馈， 试了一下，可以的！ 下个版本修复～

**Comment by theowenyoung** [comment]
https://github.com/immersive-translate/next-immersive-translate/releases/tag/v0.0.35

已修复～
