### ISSUE TITLE
对于谷歌搜索上的更多有价值信息，没有识别和翻译

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/next-immersive-translate#3]
![image](https://user-images.githubusercontent.com/38101170/210670707-eae819e9-6a9b-4167-bed7-fb66293aef9a.png)

对比其他插件

![image](https://user-images.githubusercontent.com/38101170/210670700-d6be09a5-cba1-4970-be1d-0e694b189090.png)

**Comment by theowenyoung** [comment]
https://github.com/immersive-translate/next-immersive-translate/releases/tag/v0.0.35

感谢反馈，已添加更多翻译项，如果后续还有需要补充的，请贴一下搜索的网址～

**Comment by Andy-AO** [comment]
> https://github.com/immersive-translate/next-immersive-translate/releases/tag/v0.0.35
> 
> 感谢反馈，已添加更多翻译项，如果后续还有需要补充的，请贴一下搜索的网址～

这是截图的那个网址，如果以后有更多的，会继续补充

[RECOVER Initiative - Google Search --- 恢复计划 - Google 搜索](https://www.google.com/search?q=RECOVER+Initiative)

**Comment by theowenyoung** [comment]
<img width="820" alt="image" src="https://user-images.githubusercontent.com/62473795/211109711-cf16931c-f578-441c-a2bb-4b6a1f274043.png">
