### ISSUE TITLE
在谷歌搜索中「翻译页面全部区域」和「立即翻译到页面底部」都会导致自动刷新

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/next-immersive-translate#4]
在我的机子上 100% 复现该问题

[tocilizumab site:www.healthrising.org - Google Search](https://www.google.com/search?q=tocilizumab+site%3Awww.healthrising.org&gl=us&gbv=2&sei=j0-3Y8OJI9b0-Qb7jb2oDQ)

**Comment by theowenyoung** [comment]
https://github.com/immersive-translate/next-immersive-translate/releases/tag/v0.0.35

感谢反馈，已解决！
