### ISSUE TITLE
维基百科公式显示错误

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/next-immersive-translate#5]
不能正确处理维基百科上的公式

# 维基百科公式处理问题

![image](https://user-images.githubusercontent.com/38101170/210942888-bd443cff-f4df-4f2b-83ff-b9c5177fcc36.png)

# Edge 自带的翻译工具正确处理了公式

![image](https://user-images.githubusercontent.com/38101170/210943000-30309ab8-bebd-4fd1-a1f0-b13312c4e678.png)

# 链接

[Human herpesvirus 6 - Wikipedia --- 人类疱疹病毒 6 - 维基百科，免费的百科全书](https://en.wikipedia.org/wiki/Human_herpesvirus_6)

**Comment by Andy-AO** [comment]
> https://github.com/immersive-translate/next-immersive-translate/releases/tag/v0.0.35
> 
> 感谢反馈，已解决！

Thanks♪(･ω･)ﾉ

**Comment by Andy-AO** [comment]
> https://github.com/immersive-translate/next-immersive-translate/releases/tag/v0.0.35
> 
> 感谢反馈，已解决！

经过测试，的确大幅改善了，但公式还是显示不出来，你那边现在能显示出来吗？

![image](https://user-images.githubusercontent.com/38101170/211117184-b6690d8e-0b53-4fdc-b44c-26f800927b5a.png)

**Comment by theowenyoung** [comment]
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/62473795/211147375-4e11d0a9-f485-4482-afa5-97caf2b5eebe.png">

我这显示是这样。

**Comment by theowenyoung** [comment]
我加了一个特殊规则，刷新一下配置页面的 About 页面就生效了。

现在是这样：

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/62473795/211147488-a8a45261-6aa9-4619-a137-60bb1ed509f5.png">

**Comment by omarkhallouf50-commits** [comment]
Open
