### ISSUE TITLE
对于维基百科有些化学式的处理，好像存在问题

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/next-immersive-translate#6]
![image](https://user-images.githubusercontent.com/38101170/211116709-10be9d9a-95f3-4f12-bd1e-f8e70f696546.png)
# 网址
[Erythritol - Wikipedia](https://en.wikipedia.org/wiki/Erythritol#Chemical_properties)

**Comment by theowenyoung** [comment]
已修复，不过是针对这个站点做的修复，不是通用的，后面再看看还有没有类似问题

**Comment by Andy-AO** [comment]
> 已修复，不过是针对这个站点做的修复，不是通用的，后面再看看还有没有类似问题

有些数学公式，似乎有类似的问题

![image](https://user-images.githubusercontent.com/38101170/211171297-014c83a4-7d11-4b88-a58e-4284a2d758d7.png)

# 链接

[Riemann hypothesis - Wikipedia --- 黎曼假设 - 维基百科](https://en.wikipedia.org/wiki/Riemann_hypothesis)

**Comment by theowenyoung** [comment]
刷新一下About页面， 更新了一下规则，可以适配这个页面了

**Comment by Andy-AO** [comment]
> 刷新一下About页面， 更新了一下规则，可以适配这个页面了

![image](https://user-images.githubusercontent.com/38101170/211171847-e411c3f0-52ec-4964-89fa-959c5fbd57ca.png)

之前的问题已经解决，但是好像有个新的问题，就是这段翻译错误地出现在了顶部

**Comment by theowenyoung** [comment]
确实..

我晚点有时间要重新研究一下，可能是目前的解决方案不太好，可能要重新想想怎么实现。

**Comment by theowenyoung** [comment]
确认是bug，新版已修复。
