### ISSUE TITLE
翻译插件无响应，动画停止

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/next-immersive-translate#7]
# 问题
![image](https://user-images.githubusercontent.com/38101170/211124460-feb59eaa-12ed-40aa-9bd0-3a88c6bfc6ed.png)

1. 不太可能是网络的问题，因为使用谷歌翻译的别的插件，这个时候是可以成功翻译的，而且速度相当快。
2. 虽然实际上是翻译失败了，但是没有给出翻译失败的提示，而且转圈的那个动画停止了，变成静态图片了，给人的感觉是程序卡住了。(转圈动画变成静态图片并不意味着这个问题必然出现，有的时候动画是静止的，但是翻译仍然会出现，不过在这个问题出现的时候，似乎转圈的话必然会变成静态的，没有遇见过动态的转圈动画伴随该问题)
3. 这个问题不是每次都会出现，而是偶发的。尝试去复现的时候发现有时候会复现失败，清除缓存之后复现又成功了，清除缓存，可能有助于复现该问题。
4. 现在我的设置是只要是英文网站就自动翻译，但是在之前没有打开自动翻译的时候，也会出现这样的问题。

# 网址
[T helper cell - Wikipedia](https://en.wikipedia.org/wiki/T_helper_cell#Th1/Th2_model)

**Comment by theowenyoung** [comment]
待确认

**Comment by Andy-AO** [comment]
> 待确认

这个无响应的问题非常影响体验，我为了帮助捉虫这里给了个视频，很完整的展现了出现的过程，也修正了之前说法中的错误，即转圈动画出现的时候问题就不会出现，实际上，问题也会出现。


https://user-images.githubusercontent.com/38101170/211172816-11e10068-df55-4c79-b745-e9f2c5735ca8.mp4

1080p的体积太大传不了，这里传个720p的将就看一下，看出问题来应该是可以的

**Comment by theowenyoung** [comment]
是不是亚马逊网页最容易出现这个问题？ 你可以贴一下经常出现这个的地址？

**Comment by Andy-AO** [comment]
> 是不是亚马逊网页最容易出现这个问题？ 你可以贴一下经常出现这个的地址？

出现这种问题的网页还挺多的，目前还没总结出什么规律，亚马逊这个我本来以为是没问题的，结果有问题了，再用用看吧

**Comment by theowenyoung** [comment]
发现了一个会导致这个问题的bug， 就是检测网址变化的时候，之前没有考虑 网址里hash 变化，导致会 清理页面数据。 旧有的一些未翻译的段落就会 一直loading.

但是不确定对你的情况下，是否有好转，观察下。

**Comment by Andy-AO** [comment]
> 发现了一个会导致这个问题的bug， 就是检测网址变化的时候，之前没有考虑 网址里hash 变化，导致会 清理页面数据。 旧有的一些未翻译的段落就会 一直loading.
> 
> 新版本已修复这个bug。
> 
> 但是不确定对你的情况下，是否有好转，观察下。

好的，我会开启自动翻译，有没有这个问题可能今天之内就能知道，因为此前的版本，此问题经常每天出现很多次

**Comment by Andy-AO** [comment]
> 发现了一个会导致这个问题的bug， 就是检测网址变化的时候，之前没有考虑 网址里hash 变化，导致会 清理页面数据。 旧有的一些未翻译的段落就会 一直loading.
> 
> 新版本已修复这个bug。
> 
> 但是不确定对你的情况下，是否有好转，观察下。

问题依旧，清除缓存，然后打开之前那两个网页，问题立即就出现了，赶紧录屏。或许清除缓存这个步骤很重要。

https://user-images.githubusercontent.com/38101170/211220571-d612ef35-d25d-477f-8c5b-dfd036e7689c.mp4

**Comment by Andy-AO** [comment]
发现了更多的线索，这个问题和缓存机制存在很大的关系，因为关闭缓存之后问题就立即消失了，这里有录屏可以作为参考

https://user-images.githubusercontent.com/38101170/211220957-29aaf1fe-d69c-4de8-8a35-e01d0621cfbf.mp4

**Comment by theowenyoung** [comment]
你可以 点击 左下角 开发者设置， 在那里 打开 日志， 然后在页面上 右键 ，审查元素， 然后看下里面的 Console 里的日志输出。看看有没有错误。 我这边测试缓存清理，好像一直没有遇到问题。

然后截图看看日志～

**Comment by theowenyoung** [comment]
新版本可以了。

我在想会不会是平台问题，因为我是用mac 测试的，firefox和chrome都有测试。
你的浏览器是chrome吧？

**Comment by Andy-AO** [comment]
> 新版本可以了。
> 
> 我在想会不会是平台问题，因为我是用mac 测试的，firefox和chrome都有测试。 你的浏览器是chrome吧？

我的平台是新 Edge，我换个浏览器试试看

**Comment by Andy-AO** [comment]
> 你可以 点击 左下角 开发者设置， 在那里 打开 日志， 然后在页面上 右键 ，审查元素， 然后看下里面的 Console 里的日志输出。看看有没有错误。 我这边测试缓存清理，好像一直没有遇到问题。
> 
> 然后截图看看日志～

就在刚刚问题出现了，然后刚好日志已经开了，我截了个图

![image](https://user-images.githubusercontent.com/38101170/211223469-17c57337-05e4-4dff-8ef2-b84b235ee3df.png)

![image](https://user-images.githubusercontent.com/38101170/211223474-ca0cde28-bcd0-467e-a51b-5e3503f563c9.png)

日志文件呢，也给保存下来了

[immersive translator_github.com-1673219030448.log](https://github.com/immersive-translate/next-immersive-translate/files/10369697/immersive.translator_github.com-1673219030448.log)

**Comment by Andy-AO** [comment]
目前的浏览器版本是这个，准备换新 Chrome 试试看
![image](https://user-images.githubusercontent.com/38101170/211223588-16ffc5b9-02b4-4921-9f6b-4bff28c31400.png)

**Comment by theowenyoung** [comment]
似乎没有出错的日志，那个出错的地方应该是另外的插件报错。

**Comment by Andy-AO** [comment]
直接在浏览器提供的错误收集中发现了问题，不过不清楚是不是和这个情况有关

![image](https://user-images.githubusercontent.com/38101170/211224315-efa2e513-4ea3-43eb-9a8a-893bcfa5bb59.png)

目前有个初步的测试结果，就是和我用的Edge浏览器的版本应该是没有关系的，我用了别的Edge浏览器问题仍然会出现，刚开始认为好了，重复清除缓存几次之后又出现了

![image](https://user-images.githubusercontent.com/38101170/211224342-69f8d2ec-fd52-45b8-b791-cb9f4c5e797d.png)

之后我又用了新的chrome，问题仍然是出现了，所以说我认为这个和平台关系应该是不大的

**Comment by Andy-AO** [comment]
使用chrome测试的时候，在后面我录了视频
https://user-images.githubusercontent.com/38101170/211224497-d5395dfe-f8f7-4835-bc9f-6a18c2a45e0f.mp4

**Comment by Andy-AO** [comment]
换了浏览器问题仍然没能解决，我认为最大的可能性还是复现的步骤出了问题。

**Comment by theowenyoung** [comment]
好吧，所以感觉问题其实是缓存哪里出现了问题。

开启缓存后，它会优先寻找缓存，但是缓存迟迟不返回任何结果，也不报错，所以请求可能就一直挂起了？

你可以暂时关掉缓存使用，我研究下.. 估计要晚上才有时间看了。

**Comment by Andy-AO** [comment]
> 好吧，所以感觉问题其实是缓存那里出现了问题。
> 
> 开启缓存后，它会优先寻找缓存，但是缓存迟迟不返回任何结果，也不报错，所以请求可能就一直挂起了？
> 
> 你可以暂时关掉缓存使用，我研究下.. 估计要晚上才有时间看了。

辛苦了，辛苦了，我关掉缓存使用吧，看看会怎么样

**Comment by Andy-AO** [comment]
> 好吧，所以感觉问题其实是缓存那里出现了问题。
> 
> 开启缓存后，它会优先寻找缓存，但是缓存迟迟不返回任何结果，也不报错，所以请求可能就一直挂起了？
> 
> 你可以暂时关掉缓存使用，我研究下.. 估计要晚上才有时间看了。

我觉得最新的这个错误收集结果可能会有帮助，我好像看到了数据库查询错误

![image](https://user-images.githubusercontent.com/38101170/211224722-f7fcf672-32cf-40b8-aec8-bbaf94ab640a.png)

**Comment by theowenyoung** [comment]
这个错误可能是 页面脚本和后台脚本通信的时候可能出现问题，这里确实代码里可能有坑，我明天排查下，刚提交了一个新版本，加了一个超时的限制，这样理论上应该不会一直卡了。

**Comment by Andy-AO** [comment]
测试发现该问题已解决
