### ISSUE TITLE
当开启「翻译页面全部区域」时，谷歌搜索页面错位

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/next-immersive-translate#8]
![image](https://user-images.githubusercontent.com/38101170/211144245-6dd1cf3e-8117-43dc-8e76-cc00417ba354.png)
# 链接
[bpm heart - Google Search --- bpm 心脏 - Google 搜索](https://www.google.com.hk/search?q=bpm+heart)

**Comment by theowenyoung** [comment]
试下 最新版本呢 刚发了最新的 好像我这没问题

**Comment by Andy-AO** [comment]
> 试下 最新版本呢 刚发了最新的 好像我这没问题

![image](https://user-images.githubusercontent.com/38101170/211171532-b8ba58c5-9252-4aab-9292-5b9dfe96ed7a.png)
**尝试了最新版本问题仍然存在**
感觉这个问题的关键在于，对于 All Images News 等翻译的样式出了问题
如果这个地方是中文，那么这个问题将不会出现
所以建议登录谷歌账号，将显示样式设置为英文进行测试

**Comment by theowenyoung** [comment]
嗯，可以复现。

我试了用 腾讯翻译翻译这个页面： https://chrome.google.com/webstore/detail/%E8%85%BE%E8%AE%AF%E7%BF%BB%E8%AF%91/lkjkfecdnfjopaeaibboihfkmhdjmanm?hl=zh-CN

适配的还挺好的。

所以可能是我选取的路线 不太好。

**Comment by theowenyoung** [comment]
感觉应对大多数普通新闻网站还挺好的，但是面对这种复杂的网页，就会出问题。

**Comment by Andy-AO** [comment]
> 感觉应对大多数普通新闻网站还挺好的，但是面对这种复杂的网页，就会出问题。

感觉之前主要的设计目标是翻译文章，而不是全部的网页内容。软件就是这样嘛，但要扩展用途的时候，代码通常都会出现问题。可以参考「划词翻译」，这个不是开源的，但是或许能够有所借鉴。

**Comment by Andy-AO** [comment]
> 感觉应对大多数普通新闻网站还挺好的，但是面对这种复杂的网页，就会出问题。

划词翻译的实现是这样的，或许有参考价值

![image](https://user-images.githubusercontent.com/38101170/211172333-f8851305-2aca-429e-8d45-5d6d29969623.png)

**Comment by theowenyoung** [comment]
嗯，翻译整个网页的区域是这几天才添加的。 这个插件的目的是让日常使用的网站双语翻译体验更好，所以，对于像谷歌这样的网站，更倾向于适配它，只翻译重要区域。（谷歌搜索页面本身也确实非常的杂乱无章...）

**Comment by theowenyoung** [comment]
再试试，做了特殊处理~

**Comment by Andy-AO** [comment]
非常完美
