### ISSUE TITLE
亚马逊上商品的标题可能会不翻译

### ISSUE THREAD

**Issue by Andy-AO** [immersive-translate/next-immersive-translate#9]
![image](https://user-images.githubusercontent.com/38101170/211173927-de9bddda-e083-4209-a520-524ff2297794.png)

这个似乎和商品标题的长度有关，我看到短的是可以翻译的

![image](https://user-images.githubusercontent.com/38101170/211173954-66016793-59a3-4b7f-9a63-19fc76cb60fa.png)

# link
[Amazon.com : POTS --- 亚马逊网站：POTS](https://www.amazon.com/s?k=POTS&rh=n%3A154606011&ref=nb_sb_noss)

**Comment by theowenyoung** [comment]
已添加亚马逊的支持
